/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionBar: typeof import('./components/ActionBar.vue')['default']
    ActionsMenu: typeof import('./components/ActionsMenu.vue')['default']
    AppBreadcrumb: typeof import('./components/AppBreadcrumb.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BaseButton: typeof import('./components/buttons/BaseButton.vue')['default']
    BaseDialog: typeof import('./components/BaseDialog.vue')['default']
    BasePage: typeof import('./components/BasePage.vue')['default']
    Btn: typeof import('./components/buttons/Btn.vue')['default']
    BtnCancel: typeof import('./components/buttons/BtnCancel.vue')['default']
    BtnDelete: typeof import('./components/buttons/BtnDelete.vue')['default']
    BtnEdit: typeof import('./components/buttons/BtnEdit.vue')['default']
    BtnExport: typeof import('./components/buttons/BtnExport.vue')['default']
    BtnFilter: typeof import('./components/buttons/BtnFilter.vue')['default']
    BtnManageUsers: typeof import('./components/buttons/BtnManageUsers.vue')['default']
    BtnNew: typeof import('./components/buttons/BtnNew.vue')['default']
    BtnSave: typeof import('./components/buttons/BtnSave.vue')['default']
    BtnSearch: typeof import('./components/buttons/BtnSearch.vue')['default']
    BtnView: typeof import('./components/buttons/BtnView.vue')['default']
    DataTable: typeof import('./components/DataTable.vue')['default']
    ExampleUsage: typeof import('./components/buttons/ExampleUsage.vue')['default']
    ExportActions: typeof import('./components/ExportActions.vue')['default']
    FiltersCard: typeof import('./components/FiltersCard.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    ModalButtons: typeof import('./components/ModalButtons.vue')['default']
    PageHeader: typeof import('./components/PageHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopbarActions: typeof import('./components/TopbarActions.vue')['default']
  }
}
