/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionBar: typeof import('./components/ActionBar.vue')['default']
    ActionMenu: typeof import('./components/ActionMenu.vue')['default']
    ActionMenuItem: typeof import('./components/ActionMenuItem.vue')['default']
    AppBreadcrumb: typeof import('./components/AppBreadcrumb.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppointmentModal: typeof import('./components/modals/AppointmentModal.vue')['default']
    AppointmentViewModal: typeof import('./components/modals/AppointmentViewModal.vue')['default']
    BaseDialog: typeof import('./components/BaseDialog.vue')['default']
    BasePage: typeof import('./components/BasePage.vue')['default']
    DataTable: typeof import('./components/DataTable.vue')['default']
    DeleteConfirmModal: typeof import('./components/modals/DeleteConfirmModal.vue')['default']
    ExportActions: typeof import('./components/ExportActions.vue')['default']
    FiltersCard: typeof import('./components/FiltersCard.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    MobileActionButtons: typeof import('./components/MobileActionButtons.vue')['default']
    PageHeader: typeof import('./components/PageHeader.vue')['default']
    PermissionGuard: typeof import('./components/PermissionGuard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToastContainer: typeof import('./components/ToastContainer.vue')['default']
    TopbarActions: typeof import('./components/TopbarActions.vue')['default']
  }
}
